version: "2"

run:
  timeout: 10m
  tests: true

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: true
      check-blank: true
    funlen:
      lines: 100
      statements: 50
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
    gocyclo:
      min-complexity: 15
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
    gosec:
      excludes:
        - G204
        - G304
    govet:
      enable:
        - shadow
    lll:
      line-length: 120
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    staticcheck:
      checks:
        - all
    unparam:
      check-exported: false
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - mnd
          - funlen
          - gocognit
          - gocyclo
          - dupl
      - path: pkg/mocks/
        linters:
          - mnd
          - funlen
          - gocognit
          - gocyclo
          - dupl
          - gocritic
          - staticcheck
      - source: "^//go:generate "
        linters:
          - lll
      - path: '(.+)\.go$'
        text: 'declaration of "(err|ctx)" shadows declaration at'
      - path: '(.+)\.go$'
        text: 'G104: Errors unhandled'
      - path: '(.+)\.go$'
        text: 'G204: Subprocess launched with variable'

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: 
      - github.com/SchSeba/slack-ai-assistant
